name: Update World Cup Calendar

on:

workflow_dispatch:

schedule:
- cron: "*/15 * * * *"

jobs:

update:

runs-on: ubuntu-latest

permissions:
  contents: write

steps:

  - name: Checkout
    uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"

  - name: Install
    run: |
      pip install -r requirements.txt

  - name: Generate Calendar
    run: |
      python generate_ics.py

  - name: Commit
    run: |
      git config user.name github-actions
      git config user.email github-actions@github.com

      git add worldcup_2026_final.ics
      git add cache.json

      git diff --cached --quiet || \
      git commit -m "update world cup calendar"

      git push
