name: Update World Cup Calendar

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python generate_ics.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "calendar update"
            git push
          fi
